name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.X

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI 
        run: npm install -g gatsby-cli@4.13.0

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" > ~/.ssh/known_hosts

      - name: SFTP upload
        run: sftp -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.REMOTE_HOST }} <<< $'cd ${{ secrets.DESTINATION_PATH }} \n put -r public/*'
