name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x    

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI 
        run: npm install -g gatsby-cli@4.13.0

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public
